/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'P1_Base' 
 * Target:  'K8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f3xx.h"

/* Keil::Device&Standalone:Startup@1.11.3 */
#define RTE_DEVICE_STARTUP_STM32F3XX    /* Device Startup for STM32F3 */


#endif /* RTE_COMPONENTS_H */
